# Generated by Django 5.1.7 on 2025-03-10 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamemessage',
            name='time',
            field=models.DateTimeField(),
        ),
    ]
